import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Store } from '../src/store.js';
import { createUserBot } from '../src/user-bot.js';
import { DAY_MS, PLANS } from '../src/premium-store.js';
import { partnerSummary } from '../src/premium-bot.js';

async function fixture(run){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'anon-premium-')),filename=path.join(dir,'chat.db');
 const store=new Store(filename),bot=createUserBot('123456:offline-test',filename,{store});
 bot.botInfo={id:123456,is_bot:true,first_name:'Test',username:'PremiumTestBot'};
 const sent=[];let intercept=null,seq=1;
 bot.api.config.use(async(_prev,method,payload)=>{sent.push({method,...payload});if(intercept){const r=await intercept(method,payload);if(r!==undefined)return r;}return {ok:true,result:method==='getStarTransactions'?{transactions:[]}:{message_id:99,date:1,chat:{id:payload.chat_id,type:'private'},text:payload.text}};});
 for(const [id,gender]of [[1,'male'],[2,'female'],[3,'female']]){store.upsertUser(id,'private_name_'+id);store.setProfile(id,{age:25,gender});}
 const from=id=>({id,is_bot:false,first_name:'Test'}),chat=id=>({id,type:'private'});
 const send=(id,text)=>bot.handleUpdate({update_id:seq++,message:{message_id:seq,date:1,from:from(id),chat:chat(id),text,...(text.startsWith('/')?{entities:[{type:'bot_command',offset:0,length:text.split(' ')[0].length}]}:{})}});
 const callback=(id,data)=>bot.handleUpdate({update_id:seq++,callback_query:{id:String(seq),from:from(id),chat_instance:'test',data,message:{message_id:44,date:1,chat:chat(id),text:'button'}}});
 const checkout=(id,payment)=>bot.handleUpdate({update_id:seq++,pre_checkout_query:{...payment,from:from(id)}});
 const paid=(id,payment)=>bot.handleUpdate({update_id:seq++,message:{message_id:seq,date:1,from:from(id),chat:chat(id),successful_payment:payment}});
 const refunded=(id,payment)=>bot.handleUpdate({update_id:seq++,message:{message_id:seq,date:1,from:from(id),chat:chat(id),refunded_payment:payment}});
 const order=(id=1,plan='week',now=Date.now(),consent=true)=>{
  const o=store.premium.createOrder(id,123456,plan,now);if(consent)store.premium.acceptOrder(id,123456,o.id,now);
  const p={id:'checkout-'+o.id,currency:'XTR',total_amount:o.stars,invoice_payload:store.premium.payload(o),telegram_payment_charge_id:'charge-'+o.id,provider_payment_charge_id:''};
  return {o,p};
 };
 const purchase=(id=1,plan='week',now=Date.now())=>{const {o,p}=order(id,plan,now);store.premium.approve(id,123456,p,now);return {o,p,r:store.premium.applyPayment(id,123456,p,now)};};
 try{await run({dir,filename,store,bot,sent,send,callback,checkout,paid,refunded,order,purchase,setIntercept:fn=>{intercept=fn;}});}
 finally{bot.stopSessionRetention();await bot.stopPremium();await bot.drainArchiveJobs();store.close();fs.rmSync(dir,{recursive:true,force:true});}
}

test('approved prices are fixed in Stars',()=>{assert.deepEqual(Object.values(PLANS).map(p=>[p.days,p.stars]),[[7,25],[30,75],[90,180]]);});
test('an invoice and pre-checkout alone never grant premium',()=>fixture(async({store,order})=>{const {p}=order();assert.equal(store.premium.active(1),false);store.premium.approve(1,123456,p);assert.equal(store.premium.active(1),false);}));
test('checkout requires recorded acceptance of terms',()=>fixture(async({store,order})=>{const {p}=order(1,'week',Date.now(),false);assert.throws(()=>store.premium.approve(1,123456,p),/expired_or_paid/);}));
test('checkout validates owner, bot, currency, amount and expiry',()=>fixture(async({store,order})=>{const now=Date.now(),{p}=order(1,'week',now);for(const [uid,bid,payment]of [[2,123456,p],[1,9,p],[1,123456,{...p,currency:'RUB'}],[1,123456,{...p,total_amount:1}]])assert.throws(()=>store.premium.approve(uid,bid,payment,now));assert.throws(()=>store.premium.approve(1,123456,p,now+900000));}));
test('second distinct checkout for the same invoice is rejected',()=>fixture(async({store,order})=>{const {p}=order();store.premium.approve(1,123456,p);store.premium.approve(1,123456,p);assert.throws(()=>store.premium.approve(1,123456,{...p,id:'another-query'}),/already_started/);}));
test('successful payment grants exactly the purchased duration',()=>fixture(async({store,purchase})=>{const now=Date.now(),{r}=purchase(1,'month',now);assert.equal(r.until,now+30*DAY_MS);assert.equal(store.premium.active(1),true);}));
test('payment replay is idempotent',()=>fixture(async({store,purchase})=>{const {p,r}=purchase();const second=store.premium.applyPayment(1,123456,p);assert.equal(second.duplicate,true);assert.equal(second.until,r.until);assert.equal(store.premium.recentPayments().length,1);}));
test('another charge against an already paid order does not add time',()=>fixture(async({store,purchase})=>{const {p,r}=purchase();assert.throws(()=>store.premium.applyPayment(1,123456,{...p,telegram_payment_charge_id:'second-charge'}));assert.equal(store.premium.until(1),r.until);}));
test('a charge cannot be reused for another order or user',()=>fixture(async({store,purchase,order})=>{const {p}=purchase();const other=order(2);store.premium.approve(2,123456,other.p);assert.throws(()=>store.premium.applyPayment(2,123456,{...other.p,telegram_payment_charge_id:p.telegram_payment_charge_id}),/charge_mismatch/);assert.equal(store.premium.active(2),false);}));
test('renewal extends existing time and expired access starts from now',()=>fixture(async({store,purchase})=>{const now=Date.now();purchase(1,'week',now);purchase(1,'month',now+1000);assert.equal(store.premium.until(1),now+37*DAY_MS);purchase(1,'week',now+40*DAY_MS);assert.equal(store.premium.until(1),now+47*DAY_MS);}));
test('premium and ledger survive reopening the database',()=>fixture(async({filename,purchase,store})=>{const {r}=purchase();const reopened=new Store(filename);try{assert.equal(reopened.premium.until(1),r.until);assert.equal(reopened.premium.recentPayments().length,1);}finally{reopened.close();}}));
test('refund is idempotent and retains a separate purchase',()=>fixture(async({store,purchase})=>{const now=Date.now(),first=purchase(1,'week',now);purchase(1,'month',now+1000);store.premium.refund(first.p.telegram_payment_charge_id,1,now+2000);const until=store.premium.until(1);assert.equal(until,now+1000+30*DAY_MS);store.premium.refund(first.p.telegram_payment_charge_id,1,now+3000);assert.equal(store.premium.until(1),until);assert.equal(store.premium.recentPayments().length,2);}));
test('refund arriving before receipt never grants later access',()=>fixture(async({store,order})=>{const {p}=order();store.premium.approve(1,123456,p);store.premium.recordRefund(1,123456,p);const r=store.premium.applyPayment(1,123456,p);assert.equal(r.refunded,true);assert.equal(store.premium.active(1),false);}));
test('refunded receipt replay never restores entitlement',()=>fixture(async({store,purchase})=>{const {p}=purchase();store.premium.refund(p.telegram_payment_charge_id,1);const replay=store.premium.applyPayment(1,123456,p);assert.equal(replay.refunded,true);assert.equal(store.premium.active(1),false);}));
test('premium bypasses the quota without consuming free matches',()=>fixture(async({store,purchase})=>{store.db.prepare("INSERT INTO filtered_usage VALUES(1,date('now'),50)").run();assert.equal(store.filteredRemaining(1),0);purchase();assert.equal(store.filteredRemaining(1),Infinity);store.enqueue(1,'filtered','any',18,99);assert.equal(store.enqueue(2,'random').status,'matched');assert.equal(store.db.prepare('SELECT matches FROM filtered_usage WHERE user_id=1').get().matches,50);store.premium.db.prepare('UPDATE premium_access SET until_ms=0 WHERE user_id=1').run();assert.equal(store.filteredRemaining(1),0);}));
test('premium does not cross the minor adult boundary or bypass blocks',()=>fixture(async({store,purchase})=>{purchase();store.setProfile(2,{age:17});store.enqueue(1,'filtered','any',12,99);assert.equal(store.enqueue(2,'random').status,'waiting');store.reportAndBlock(1,3);store.enqueue(1,'random');assert.equal(store.enqueue(3,'random').status,'waiting');}));
test('profile details are hidden by default, and revealing never exposes identity',()=>fixture(async({store,purchase})=>{purchase();store.enqueue(1,'random');store.enqueue(2,'random');let text=partnerSummary(store,1,2);assert.match(text,/скрыты/);assert.ok(!text.includes('25'));store.premium.setVisibility(2,true);text=partnerSummary(store,1,2);assert.match(text,/девушка, 25/);assert.ok(!text.includes('private_name'));assert.ok(!text.includes('ID'));store.premium.setVisibility(2,false);assert.match(partnerSummary(store,1,2),/скрыты/);}));
test('non-premium viewers never receive the other profile',()=>fixture(async({store})=>{store.enqueue(1,'random');store.enqueue(2,'random');store.premium.setVisibility(2,true);assert.equal(partnerSummary(store,1,2),'');}));
test('premium menu and partner command are never forwarded into an active chat',()=>fixture(async({store,send,sent})=>{store.enqueue(1,'random');store.enqueue(2,'random');await send(1,'/premium');await send(1,'/partner');assert.equal(store.getUser(1).partner_id,2);assert.ok(!sent.some(x=>x.method==='copyMessage'));assert.ok(sent.some(x=>x.text?.includes('Без автосписаний')));}));
test('invoice is sent only after acceptance and uses XTR with one price',()=>fixture(async({store,callback,sent})=>{await callback(1,'premium:plan:week');assert.ok(!sent.some(x=>x.method==='sendInvoice'));const o=store.premium.db.prepare('SELECT * FROM premium_orders WHERE user_id=1').get();assert.equal(o.accepted_ms,null);await callback(1,'premium:accept:'+o.id);const invoice=sent.find(x=>x.method==='sendInvoice');assert.equal(invoice.currency,'XTR');assert.equal(invoice.provider_token,'');assert.equal(invoice.prices.length,1);assert.equal(invoice.prices[0].amount,25);assert.equal(invoice.start_parameter,'premium');assert.ok(store.premium.order(o.id).accepted_ms);}));
test('another user cannot accept someone else invoice',()=>fixture(async({order,callback,sent})=>{const {o}=order(1,'week',Date.now(),false);await callback(2,'premium:accept:'+o.id);assert.ok(!sent.some(x=>x.method==='sendInvoice'));}));
test('successful payment in a live chat activates without breaking or relaying it',()=>fixture(async({store,checkout,paid,sent,order})=>{store.enqueue(1,'random');store.enqueue(2,'random');const {p}=order();await checkout(1,p);assert.equal(store.premium.active(1),false);await paid(1,p);await paid(1,p);assert.equal(store.premium.active(1),true);assert.equal(store.getUser(1).partner_id,2);assert.ok(!sent.some(x=>x.method==='copyMessage'));assert.equal(sent.filter(x=>x.text?.includes('Премиум включён')).length,1);}));
test('invalid paid receipt is retained for review without granting access',()=>fixture(async({store,order,paid})=>{const {p}=order();await paid(1,{...p,total_amount:1});assert.equal(store.premium.active(1),false);assert.equal(store.premium.db.prepare('SELECT COUNT(*) n FROM payment_anomalies').get().n,1);}));
test('banned users cannot check out but can contact payment support',()=>fixture(async({store,checkout,order,send,sent})=>{const {p}=order();store.banUser(1);await checkout(1,p);assert.equal(sent.find(x=>x.method==='answerPreCheckoutQuery').ok,false);await send(1,'/paysupport Нужен возврат');assert.equal(store.premium.openSupport().length,1);}));
test('accepted payment is not lost if a user is banned between checkout and receipt',()=>fixture(async({store,checkout,order,paid})=>{const {p}=order();await checkout(1,p);store.banUser(1);await paid(1,p);assert.equal(store.premium.recentPayments().length,1);assert.equal(store.isBanned(1),true);}));
test('payment support commands are private and never relayed',()=>fixture(async({store,send,sent})=>{store.enqueue(1,'random');store.enqueue(2,'random');await send(1,'/paysupport Мой платёж не появился');assert.equal(store.premium.openSupport()[0].text,'Мой платёж не появился');assert.ok(!sent.some(x=>x.method==='copyMessage'));assert.equal(store.getUser(1).partner_id,2);}));
test('payment confirmation bypasses a slow chat message',()=>fixture(async({store,send,checkout,order,setIntercept,sent})=>{store.enqueue(1,'random');store.enqueue(2,'random');let release,started;const wait=new Promise(r=>{started=r;});setIntercept(async method=>{if(method==='copyMessage'){started();await new Promise(r=>{release=r;});}});const slow=send(1,'slow');await wait;const {p}=order();await checkout(1,p);assert.equal(sent.find(x=>x.method==='answerPreCheckoutQuery').ok,true);release();await slow;}));
test('refund service message revokes only the corresponding entitlement',()=>fixture(async({store,purchase,refunded})=>{const {p}=purchase();await refunded(1,p);assert.equal(store.premium.active(1),false);await refunded(1,p);assert.equal(store.premium.recentPayments().length,1);}));
test('reconciliation restores a missed receipt once from Telegram ledger',()=>fixture(async({store,bot,order,setIntercept})=>{const {p}=order();store.premium.approve(1,123456,p);setIntercept(method=>method==='getStarTransactions'?{ok:true,result:{transactions:[{id:p.telegram_payment_charge_id,date:Math.floor(Date.now()/1000),amount:25,source:{type:'user',transaction_type:'invoice_payment',user:{id:1},invoice_payload:p.invoice_payload}}]}}:undefined);const first=await bot.reconcilePremium();assert.equal(first.restored,1);const until=store.premium.until(1);assert.equal((await bot.reconcilePremium()).restored,0);assert.equal(store.premium.until(1),until);}));
test('reconciliation applies an external refund',()=>fixture(async({store,bot,purchase,setIntercept})=>{const {p}=purchase();setIntercept(method=>method==='getStarTransactions'?{ok:true,result:{transactions:[{id:p.telegram_payment_charge_id,date:Math.floor(Date.now()/1000),amount:-25,receiver:{type:'user',transaction_type:'invoice_payment',user:{id:1},invoice_payload:p.invoice_payload}}]}}:undefined);await bot.reconcilePremium();assert.equal(store.premium.active(1),false);}));

test('refund reconciliation works without optional invoice payload',()=>fixture(async({store,bot,purchase,setIntercept})=>{const {p}=purchase();setIntercept(method=>method==='getStarTransactions'?{ok:true,result:{transactions:[{id:p.telegram_payment_charge_id,date:Math.floor(Date.now()/1000),amount:-25,receiver:{type:'user',transaction_type:'invoice_payment',user:{id:1}}}]}}:undefined);await bot.reconcilePremium();assert.equal(store.premium.active(1),false);}));
test('premium user receives only consented demographics in the match notification',()=>fixture(async({store,purchase,send,sent})=>{purchase(1);store.premium.setVisibility(2,true);await send(1,'/search');await send(2,'/search');assert.ok(sent.some(x=>x.chat_id===1&&x.text?.includes('девушка, 25')));assert.ok(!sent.some(x=>x.chat_id===2&&x.text?.includes('Анкета собеседника')));}));

test('reconciliation persists its cursor and restores the 1001st ledger entry',()=>fixture(async({store,bot,order,setIntercept,filename})=>{
 const {p}=order();store.premium.approve(1,123456,p);
 const ledger=Array.from({length:1000},(_,n)=>({id:'unrelated-'+n,date:n,amount:1,source:{type:'other'}}));
 ledger.push({id:p.telegram_payment_charge_id,date:Math.floor(Date.now()/1000),amount:25,source:{type:'user',transaction_type:'invoice_payment',user:{id:1},invoice_payload:p.invoice_payload}});
 setIntercept((method,payload)=>method==='getStarTransactions'?{ok:true,result:{transactions:ledger.slice(payload.offset,payload.offset+payload.limit)}}:undefined);
 const first=await bot.reconcilePremium();assert.equal(first.complete,false);assert.equal(first.restored,0);assert.equal(first.nextOffset,1000);
 const reopened=new Store(filename);try{assert.equal(reopened.db.prepare("SELECT next_offset FROM premium_sync_state WHERE name='stars'").get().next_offset,1000);}finally{reopened.close();}
 const second=await bot.reconcilePremium();assert.equal(second.complete,true);assert.equal(second.restored,1);assert.equal(store.premium.active(1),true);
 assert.equal(store.db.prepare("SELECT next_offset FROM premium_sync_state WHERE name='stars'").get().next_offset,0);
}));
test('failed reconciliation does not skip ahead of an unprocessed ledger page',()=>fixture(async({store,bot,setIntercept})=>{
 store.db.prepare("INSERT INTO premium_sync_state VALUES('stars',1000,?)").run(Date.now());
 setIntercept((method,payload)=>{if(method==='getStarTransactions')throw new Error('temporary failure');});
 await assert.rejects(bot.reconcilePremium(),/temporary failure/);
 assert.equal(store.db.prepare("SELECT next_offset FROM premium_sync_state WHERE name='stars'").get().next_offset,1000);
}));
